suppress fork leaks in tests

diff --git a/tests/integration_tests b/tests/integration_tests
--- a/tests/integration_tests
+++ b/tests/integration_tests
@@ -3,6 +3,7 @@ set -x
 set -e
 
 export ASAN_OPTIONS='detect_leaks=1'
+export LSAN_OPTIONS='suppressions=leak_suppression.txt print_suppressions=0'
 
 function check_valgrind_output()
 {
@@ -31,7 +32,7 @@ function shell_test()
 	echo -e $1 | bash > bash_out 2> bash_err
 	export bash_status=$?
 	set -e
-	diff minishell_out bash_out || { echo "test failed for: \"$1\""; exit 1; }
+	diff minishell_out bash_out || { echo "std output test failed for: \"$1\""; exit 1; }
 	diff minishell_err bash_err || { echo "error output test failed for: \"$1\""; exit 1; }
 	diff minishell_outfile bash_outfile || { echo "outfile of output test failed for: \"$1\""; exit 1;}
 	check_status "$1" $minishell_status $bash_status
