only output valgrind on error

diff --git a/tests/integration_tests b/tests/integration_tests
--- a/tests/integration_tests
+++ b/tests/integration_tests
@@ -4,19 +4,21 @@ set -e
 
 function shell_test()
 {
-	echo $1 | valgrind ../minishell > minishell_out #Added valgrind temporarily
+	echo $1 | valgrind --leak-check=full ../minishell > minishell_out 2>leaks_output
 	echo $1 | bash > bash_out
 	diff minishell_out bash_out || { echo "test failed for: \"$1\""; exit 1; }
+	grep -q ' 0 errors from 0 contexts' leaks_output || { echo "found valgrind error for for: \"$1\""; cat leaks_output; exit 1; }
 }
 
 function output_test()
 {
 	export OUTFILE=minishell_outfile
-	echo $1 | ../minishell > minishell_stdout
+	echo $1 | valgrind --leak-check=full ../minishell > minishell_stdout 2>leaks_output
 	export OUTFILE=bash_outfile
 	echo $1 | bash > bash_stdout
 	diff minishell_stdout bash_stdout || { echo "stdout of output test failed for: \"$1\""; exit 1;}
 	diff minishell_outfile bash_outfile || { echo "outfile of output test failed for: \"$1\""; exit 1;}
+	grep -q ' 0 errors from 0 contexts' leaks_output || { echo "found valgrind error for for: \"$1\""; cat leaks_output; exit 1; }
 }
 
 make -C ..
