move valgrind output check to separate function

diff --git a/tests/integration_tests b/tests/integration_tests
--- a/tests/integration_tests
+++ b/tests/integration_tests
@@ -2,6 +2,11 @@
 #set -x
 set -e
 
+function check_valgrind_output()
+{
+	grep -q ' 0 errors from 0 contexts' leaks_output || { echo "found valgrind error for for: \"$1\""; cat leaks_output; exit 1; }
+}
+
 function shell_test_error()
 {
 	set +e
@@ -11,7 +16,7 @@ function shell_test_error()
 	set -e
 	diff minishell_out bash_out || { echo "test failed for: \"$1\""; exit 1; }
 	diff minishell_err bash_err || { echo "error output test failed for: \"$1\""; exit 1; }
-	grep -q ' 0 errors from 0 contexts' leaks_output || { echo "found valgrind error for for: \"$1\""; cat leaks_output; exit 1; }
+	check_valgrind_output $1
 }
 
 function shell_test()
@@ -19,7 +24,7 @@ function shell_test()
 	echo -e $1 | valgrind --leak-check=full ../minishell > minishell_out 2>leaks_output
 	echo -e $1 | bash > bash_out 2> bash_err
 	diff minishell_out bash_out || { echo "test failed for: \"$1\""; exit 1; }
-	grep -q ' 0 errors from 0 contexts' leaks_output || { echo "found valgrind error for for: \"$1\""; cat leaks_output; exit 1; }
+	check_valgrind_output $1
 }
 
 function output_test()
@@ -30,7 +35,7 @@ function output_test()
 	echo -e $1 | bash > bash_stdout
 	diff minishell_stdout bash_stdout || { echo "stdout of output test failed for: \"$1\""; exit 1;}
 	diff minishell_outfile bash_outfile || { echo "outfile of output test failed for: \"$1\""; exit 1;}
-	grep -q ' 0 errors from 0 contexts' leaks_output || { echo "found valgrind error for for: \"$1\""; cat leaks_output; exit 1; }
+	check_valgrind_output $1
 }
 
 make DEBUG=1 LEAKS=1 -C ..
